export const BIRDS_DATA = [
  {
    id: "oriental-pied-hornbill",
    name: "Oriental Pied Hornbill",
    scientificName: "Anthracoceros albirostris",
    family: "Bucerotidae",
    region: "Sreemangal, Bangladesh",
    habitat: "Wet evergreen and moist deciduous forest, edge habitats",
    funFact: "To nest, the female seals herself inside a tree cavity using mud, droppings, and wood pulp. The male feeds her and the chicks through a tiny slit for weeks!",
    imageUrl: "https://upload.wikimedia.org/wikipedia/commons/8/8b/Oriental_pied_hornbill_%28Anthracoceros_albirostris%29_male_%28l%29_female_%28r%29.jpg",
    soundUrl: "https://static.inaturalist.org/sounds/1801333.wav?1773215134",
    callType: "Cackling screech",
    description: "A loud, piercing cackling 'kek-kek-kek-kek-kek' that starts off spaced and accelerates into a rapid, laughing rattle."
  },
  {
    id: "greater-racket-tailed-drongo",
    name: "Greater Racket-tailed Drongo",
    scientificName: "Dicrurus paradiseus",
    family: "Dicruridae",
    region: "Sreemangal, Bangladesh",
    habitat: "Broadleaved evergreen forests and bamboo thickets",
    funFact: "These birds are incredible vocal mimics. They imitate the calls of hawks to frighten other birds, or mimic squirrels to steal food in mixed-species flocks!",
    imageUrl: "https://upload.wikimedia.org/wikipedia/commons/8/8e/Greater_Racket-tailed-Drongo_cropped.jpg",
    soundUrl: "https://static.inaturalist.org/sounds/1736848.wav?1767974675",
    callType: "Metallic whistle & mimicry",
    description: "An astonishingly rich repertoire of deep metallic clinks, melodious whistles, and perfect mimicry of other forest birds."
  },
  {
    id: "white-rumped-shama",
    name: "White-rumped Shama",
    scientificName: "Copsychus malabaricus",
    family: "Muscicapidae",
    region: "Sreemangal, Bangladesh",
    habitat: "Dense jungle undergrowth, secondary scrub, and bamboo forest",
    funFact: "Shamas are considered one of the finest songbirds in the world. They sing with immense variety, rarely repeating the exact same whistle sequence.",
    imageUrl: "https://upload.wikimedia.org/wikipedia/commons/9/98/Copsychus_malabaricus_male_-_Khao_Yai.jpg",
    soundUrl: "https://static.inaturalist.org/sounds/1752236.mp3?1769583347",
    callType: "Melodious song",
    description: "A stunningly beautiful, flute-like song consisting of highly varied, liquid whistles, trills, and deep musical phrases."
  },
  {
    id: "asian-koel",
    name: "Asian Koel",
    scientificName: "Eudynamys scolopaceus",
    family: "Cuculidae",
    region: "Sreemangal, Bangladesh",
    habitat: "Open woodlands, gardens, agricultural lands, and dense suburbs",
    funFact: "Asian Koels are brood parasites. They lay their eggs inside the nests of House Crows, which raise the young Koel alongside their own chicks!",
    imageUrl: "https://upload.wikimedia.org/wikipedia/commons/4/41/Common_koel_%28female%29_by_N.A._Nazeer.jpg",
    soundUrl: "https://static.inaturalist.org/sounds/1733193.m4a?1767611426",
    callType: "Koel call",
    description: "A loud, echoing, hollow 'koo-el! koo-el!' that rises sharply in pitch, speed, and intensity with each repetition."
  },
  {
    id: "white-throated-kingfisher",
    name: "White-throated Kingfisher",
    scientificName: "Halcyon smyrnensis",
    family: "Alcedinidae",
    region: "Sreemangal, Bangladesh",
    habitat: "Paddy fields, wetlands, open country, and forest clearings",
    funFact: "Unlike water kingfishers, they don't depend entirely on water. They hunt on dry land, catching large insects, lizards, rodents, and small snakes!",
    imageUrl: "https://upload.wikimedia.org/wikipedia/commons/c/c4/013_White-throated_kingfisher_in_Keoladeo_National_Park_Photo_by_Giles_Laurent.jpg",
    soundUrl: "https://static.inaturalist.org/sounds/1753094.m4a?1769702309",
    callType: "Chattering laugh",
    description: "A loud, rapid, chattering laugh that descends slightly in pitch: 'kreee-kreee-kreee-kreee'."
  },
  {
    id: "lineated-barbet",
    name: "Lineated Barbet",
    scientificName: "Psilopogon lineatus",
    family: "Megalaimidae",
    region: "Sreemangal, Bangladesh",
    habitat: "Dry and moist deciduous canopy forests and orchards",
    funFact: "They use their thick, heavy bills to chisel nesting holes deep inside dead, rotting tree trunks, similar to how woodpeckers carve nests.",
    imageUrl: "https://upload.wikimedia.org/wikipedia/commons/6/61/Lineated_barbet_%28Psilopogon_lineatus%29%2C_Bangladesh.jpg",
    soundUrl: "https://static.inaturalist.org/sounds/1742118.m4a?1768524927",
    callType: "Rhythmic hoot",
    description: "A loud, bubbling, rhythmic calling that echoes through the trees, sounding like a repeated, metallic 'kutroo-kutroo-kutroo'."
  },
  {
    id: "common-iora",
    name: "Common Iora",
    scientificName: "Aegithina tiphia",
    family: "Aegithinidae",
    region: "Sreemangal, Bangladesh",
    habitat: "Forest edges, scrubby agricultural fields, and backyards",
    funFact: "During breeding displays, males puff up their feathers, fly straight up, and then spiral down to their perch like a bouncing ball of green and gold.",
    imageUrl: "https://upload.wikimedia.org/wikipedia/commons/d/d9/Common_Iora_%28Aegithina_tiphia%29_%40_KL.jpg",
    soundUrl: "https://static.inaturalist.org/sounds/1770335.wav?1771365007",
    callType: "Sliding whistle",
    description: "A long, drawn-out, clear whistle that bends or drops in pitch at the very end, followed by quick chattering notes."
  },
  {
    id: "red-junglefowl",
    name: "Red Junglefowl",
    scientificName: "Gallus gallus",
    family: "Phasianidae",
    region: "Sreemangal, Bangladesh",
    habitat: "Dense forest floor, thick scrub, and bamboo undergrowth",
    funFact: "The Red Junglefowl is the absolute primary ancestor of the domestic chicken! Domesticated chickens were bred from this wild forest bird thousands of years ago.",
    imageUrl: "https://upload.wikimedia.org/wikipedia/commons/thumb/e/ef/Red_Junglefowl_by_Tisha_Mukherjee_08.jpg/960px-Red_Junglefowl_by_Tisha_Mukherjee_08.jpg",
    soundUrl: "https://static.inaturalist.org/sounds/1730234.mp3?1767320442",
    callType: "Rooster crow",
    description: "A bright, wild rooster crow that is shorter and more abrupt than domestic ones, ending in a sudden cutoff."
  },
  {
    id: "chestnut-headed-bee-eater",
    name: "Chestnut-headed Bee-eater",
    scientificName: "Merops leschenaulti",
    family: "Meropidae",
    region: "Sreemangal, Bangladesh",
    habitat: "Open country, forest glades, streamside cliffs, and clearings",
    funFact: "They capture bees and wasps in mid-air and beat them against branches to knock out their stinger and rub off the venom before eating them!",
    imageUrl: "https://upload.wikimedia.org/wikipedia/commons/f/fc/Chestnut-headed_bee-eater_%28Merops_leschenaulti%29_Yala.jpg",
    soundUrl: "https://xeno-canto.org/sounds/uploaded/LIGVVFZJTW/XC1070976-Chestnut-headed-Bee-eater-20260106-01a-%2888%25%29-garden-Makham.wav",
    callType: "Liquid trill",
    description: "A beautiful series of sweet, liquid, rippling chirps and rolling whistles delivered from an exposed branch."
  },
  {
    id: "puff-throated-babbler",
    name: "Puff-throated Babbler",
    scientificName: "Pellorneum ruficeps",
    family: "Pellorneidae",
    region: "Sreemangal, Bangladesh",
    habitat: "Moist forest undergrowth, leaf-litter floors, and thick scrub",
    funFact: "They hop along the dark forest floor, tossing fallen leaves to find grubs. They puff out their snowy-white throat feathers when whistling.",
    imageUrl: "https://upload.wikimedia.org/wikipedia/commons/1/11/Puff_Throated_Babbler.jpg",
    soundUrl: "https://xeno-canto.org/sounds/uploaded/RGSEIIJGHA/XC1075928-PuffthroatedBabbler_MuangLong_260114_4845_edited.mp3",
    callType: "Musical whistling",
    description: "A clear, loud, whistle sequence of 3-4 rising and falling notes, phonetically translated as 'pretty-sweet-heart'."
  },
  {
    id: "asian-fairy-bluebird",
    name: "Asian Fairy-bluebird",
    scientificName: "Irena puella",
    family: "Irenidae",
    region: "Sreemangal, Bangladesh",
    habitat: "Wet evergreen forest canopies and fruit-bearing groves",
    funFact: "Males have bright glistening cobalt-blue upperparts that look like liquid velvet, while females are a quiet shade of deep turquoise-teal.",
    imageUrl: "https://upload.wikimedia.org/wikipedia/commons/8/8b/Asian_Fairy-bluebird_%28Irena_puella%29_%28cropped%29.jpg",
    soundUrl: "https://static.inaturalist.org/sounds/1768290.wav?1771190754",
    callType: "Metallic pipe",
    description: "A series of loud, ringing, liquid whistles with a highly resonant and piercing metallic bell quality."
  },
  {
    id: "black-drongo",
    name: "Black Drongo",
    scientificName: "Dicrurus macrocercus",
    family: "Dicruridae",
    region: "Sreemangal, Bangladesh",
    habitat: "Open country, farmlands, roadside wires, and woodland edges",
    funFact: "Commonly called 'King Crow' because they will fearlessly dive-bomb eagles and crows ten times their size to defend their nests!",
    imageUrl: "https://upload.wikimedia.org/wikipedia/commons/2/2a/Black_Drongo_in_Purulia_June_2025_by_Tisha_Mukherjee_02.jpg",
    soundUrl: "https://static.inaturalist.org/sounds/1812327.wav?1773887772",
    callType: "Screeching rattle",
    description: "A mix of harsh rasping shrieks, clear whistles, and alarm sounds, including mimics of local predators."
  },
  {
    id: "indian-cuckoo",
    name: "Indian Cuckoo",
    scientificName: "Cuculus micropterus",
    family: "Cuculidae",
    region: "Sylhet, Bangladesh",
    habitat: "Deciduous and evergreen forests, dense woodland canopies, and country orchards",
    funFact: "Known as 'Bou-Kotha-Kao' in Bengali, its melodic four-note call translates to 'Speak up, bride!'. It is a clever brood parasite that lays its eggs in the nests of other species.",
    imageUrl: "https://upload.wikimedia.org/wikipedia/commons/thumb/a/a2/Cuculus_micropterus_41523741.jpg/960px-Cuculus_micropterus_41523741.jpg",
    soundUrl: "https://xeno-canto.org/445434/download",
    callType: "Melodic four-note whistle",
    description: "A shy, solitary bird of the forest canopy. It is famous for its highly recognizable four-note whistle (rendered as 'one-more-bottle' in English or 'bou-kotha-kao' in Bengali) that signals the arrival of spring."
  },
  {
    id: "black-hooded-oriole",
    name: "Black-hooded Oriole",
    scientificName: "Oriolus xanthornus",
    family: "Oriolidae",
    region: "Sylhet, Bangladesh",
    habitat: "Open woodlands, gardens, cultivated lands, and forest canopies",
    funFact: "Known as 'Bene Bou' or 'Halde Pakhi' in Bengali, they build suspended hammock-like nests tightly woven between the forks of slender branches.",
    imageUrl: "https://upload.wikimedia.org/wikipedia/commons/e/ec/Black-hooded_Oriole_in_Rabindra_Sarobar_January_2025_by_Tisha_Mukherjee_01.jpg",
    soundUrl: "https://xeno-canto.org/933205/download",
    callType: "Liquid, flute-like whistling",
    description: "A stunning golden-yellow canopy dweller with a black hood and throat. Its musical, rich, and liquid flute-like whistles are a defining sound of rural Bangladesh."
  },
  {
    id: "van-hasselts-sunbird",
    name: "Van Hasselt's Sunbird",
    scientificName: "Leptocoma brasiliana",
    family: "Nectariniidae",
    region: "Sylhet Forest Reserves, Bangladesh",
    habitat: "Mangrove forests, forest edges, coastal scrub, and sub-montane forest canopies",
    funFact: "Known for its striking iridescent plumage; under sunlight, the male's throat sparkles in a brilliant amethyst-violet, contrasting with a velvet-black belly.",
    imageUrl: "https://upload.wikimedia.org/wikipedia/commons/0/05/Leptocoma_brasiliana_%28male%29_-Singapore-8a.jpg",
    soundUrl: "https://xeno-canto.org/436183/download",
    callType: "High-pitched metallic squeaks",
    description: "A tiny, hyperactive nectar-feeder with mesmerizing iridescence. Males boast metallic purple crowns, throats, and bright crimson shoulders, rendering them one of Bangladesh's most radiant woodland jewels."
  },
  {
    id: "rufous-treepie",
    name: "Rufous Treepie",
    scientificName: "Dendrocitta vagabunda",
    family: "Corvidae",
    region: "Sreemangal, Bangladesh",
    habitat: "Dry deciduous forests, open woodland, orchards, and urban gardens",
    funFact: "Known as 'Harkora' or 'Hari Chacha' in Bengali, they are highly inquisitive, opportunistic feeders, and are often seen associating in feeding flocks with drongos.",
    imageUrl: "https://upload.wikimedia.org/wikipedia/commons/7/7a/Rufous_treepie_%28Dendrocitta_vagabunda_vagabunda%29_Jahalana_pair.jpg",
    soundUrl: "https://xeno-canto.org/253498/download",
    callType: "Loud, metallic, musical bob-o-link call",
    description: "An elegant member of the crow family with an elongated tail and warm tawny, grey, and black plumage. Its loud, melodious, and glass-like calls echo across woodlands."
  },
  {
    id: "asian-barred-owlet",
    name: "Asian Barred Owlet",
    scientificName: "Glaucidium cuculoides",
    family: "Strigidae",
    region: "Lawachara National Park, Sreemangal",
    habitat: "Open forests, riverine forests, orchards, and gardens with old nesting cavities",
    funFact: "Unlike many other owls, this species is highly diurnal, frequently hunting, calling, and basking in full daylight while nesting in tree hollows.",
    imageUrl: "https://upload.wikimedia.org/wikipedia/commons/d/d8/Asian_Barred_Owlet_in_Kaziranga_National_Park_March_2025_by_Tisha_Mukherjee_01.jpg",
    soundUrl: "https://xeno-canto.org/908494/download",
    callType: "Bubbling musical warble",
    description: "A charmingly small, round-headed owl heavily barred with brown and white. It has stunning yellow eyes and a fierce personality, often active during the day."
  },
  {
    id: "striated-grassbird",
    name: "Striated Grassbird",
    scientificName: "Megalurus palustris",
    family: "Locustellidae",
    region: "Haor Basins, Sylhet, Bangladesh",
    habitat: "Tall grasslands, marshes, reedbeds, swamp edges, and wet fields",
    funFact: "Known as 'Pata-futi' or 'Dhol Ghas-pakhi' in Bengali, males perform dramatic, vertical song-flights, singing loudly as they parachute back down onto tall reeds.",
    imageUrl: "https://upload.wikimedia.org/wikipedia/commons/4/46/Striated_Grassbird_%28Megalurus_palustris%29_at_Kolkata_I_IMG_2681.jpg",
    soundUrl: "https://xeno-canto.org/933275/download",
    callType: "Loud, explosive musical song",
    description: "A large, heavily streaked brown warbler-like bird with a long, graduated tail. It is a conspicuous resident of Bangladesh's freshwater marshes and tall grasses."
  },
  {
    id: "striated-babbler",
    name: "Striated Babbler",
    scientificName: "Turdoides earlei",
    family: "Leiothrichidae",
    region: "Padma Riverbanks & wetlands, Bangladesh",
    habitat: "Tall reedbeds, elephant grass, marsh edges, and dense scrub",
    funFact: "Extremely social and noisy; they are almost never seen alone and live in tight-knit family bands of 6 to 12 birds, constantly foraging and calling together.",
    imageUrl: "https://upload.wikimedia.org/wikipedia/commons/3/39/Striated_Babbler_by_Tisha_Mukherjee_06.jpg",
    soundUrl: "https://xeno-canto.org/909641/download",
    callType: "Harsh chirping and squeaking",
    description: "A pale brown, slender babbler with fine dark streaks across its breast and back. They move through tall grass like small mice, constantly maintaining contact calls."
  },
  {
    id: "black-browed-reed-warbler",
    name: "Black-browed Reed Warbler",
    scientificName: "Acrocephalus bistrigiceps",
    family: "Acrocephalidae",
    region: "Tanguar Haor, Sunamganj, Bangladesh",
    habitat: "Wet grasslands, reedbeds, swamp thickets, and marshy lowlands",
    funFact: "An expert gymnast of the reed stalks, it can cling sideways to thin stems using its strong legs and feet while searching for hidden insects.",
    imageUrl: "https://upload.wikimedia.org/wikipedia/commons/e/e6/Acrocephalus_bistrigiceps_2742844.jpg",
    soundUrl: "https://xeno-canto.org/897375/download",
    callType: "Rhythmic chatter and mimicry",
    description: "A small, elegant winter migrant to Bangladesh's wetlands, instantly recognizable by its striking white supercilium bordered by a thick black brow."
  }
];
